CREATE TABLE IF NOT EXISTS "payments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "user_id" int NOT NULL,
  "product_id" int NOT NULL,
  "bank_account_id" int NOT NULL,
  "payment_proof_image_url" varchar(255) NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "deleted_at" timestamp
);

ALTER TABLE "payments" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
ALTER TABLE "payments" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id");
ALTER TABLE "payments" ADD FOREIGN KEY ("bank_account_id") REFERENCES "bank_accounts" ("id");