CREATE TABLE IF NOT EXISTS "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "username" varchar(255) UNIQUE NOT NULL,
  "name" varchar(255) NOT NULL,
  "password" varchar(255) NOT NULL
);
