CREATE TABLE "product_tags" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "product_id" int NOT NULL,
  "name" varchar(255) NOT NULL
);

ALTER TABLE "product_tags" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id");