CREATE TABLE IF NOT EXISTS "bank_accounts" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "user_id" int NOT NULL,
  "bank_name" varchar(255) NOT NULL,
  "bank_account_name" varchar(255) NOT NULL,
  "bank_account_number" varchar(255) NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "deleted_at" timestamp
);

ALTER TABLE "bank_accounts" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");